**优点**：精度高、对异常值不敏感、无数据输入假定

**缺点**：计算复杂度高、空间复杂度高

**适用范围**：数值型、标称型

In [1]:
import kNN

In [2]:
group, labels = kNN.createDataSet()

In [3]:
group

array([[1. , 1.1],
       [1. , 1. ],
       [0. , 0. ],
       [0. , 0.1]])

In [4]:
labels

['A', 'A', 'B', 'B']

In [5]:
group.shape

(4, 2)

In [6]:
from numpy import *
help(tile)

Help on function tile in module numpy:

tile(A, reps)
    Construct an array by repeating A the number of times given by reps.
    
    If `reps` has length ``d``, the result will have dimension of
    ``max(d, A.ndim)``.
    
    If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
    axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
    or shape (1, 1, 3) for 3-D replication. If this is not the desired
    behavior, promote `A` to d-dimensions manually before calling this
    function.
    
    If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
    Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
    (1, 1, 2, 2).
    
    Note : Although tile may be used for broadcasting, it is strongly
    recommended to use numpy's broadcasting operations and functions.
    
    Parameters
    ----------
    A : array_like
        The input array.
    reps : array_like
        The number of repetitions of `A`

In [7]:
# 0 默认是int类型
inX = [0.0, 0.0]

In [8]:
diffMat = tile(inX, (group.shape[0], 1))

In [9]:
diffMat.shape

(4, 2)

In [10]:
diffMat -= group

In [11]:
diffMat

array([[-1. , -1.1],
       [-1. , -1. ],
       [ 0. ,  0. ],
       [ 0. , -0.1]])

In [12]:
sqDiffMat = diffMat**2

In [13]:
sqDistances = sqDiffMat.sum(axis = 1)

In [14]:
sqDistances

array([2.21, 2.  , 0.  , 0.01])

In [15]:
distances = sqDistances**0.5

In [16]:
distances

array([1.48660687, 1.41421356, 0.        , 0.1       ])

In [17]:
help(argsort)

Help on function argsort in module numpy:

argsort(a, axis=-1, kind=None, order=None)
    Returns the indices that would sort an array.
    
    Perform an indirect sort along the given axis using the algorithm specified
    by the `kind` keyword. It returns an array of indices of the same shape as
    `a` that index data along the given axis in sorted order.
    
    Parameters
    ----------
    a : array_like
        Array to sort.
    axis : int or None, optional
        Axis along which to sort.  The default is -1 (the last axis). If None,
        the flattened array is used.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort under the covers and, in general, the
        actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stab

In [18]:
distances.argsort()

array([2, 3, 1, 0], dtype=int64)

In [19]:
sortedDisIndicies = distances.argsort()

In [20]:
classCount = {}

In [21]:
labels

['A', 'A', 'B', 'B']

In [22]:
labels[sortedDisIndicies[2]]

'A'

In [23]:
k = 3

In [24]:
for i in range(k):
    votelLabel = labels[sortedDisIndicies[i]]
    classCount[votelLabel] = classCount.get(votelLabel, 0) + 1

In [25]:
import operator

In [26]:
sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse = True)

In [27]:
sortedClassCount[0][0]

'B'

In [28]:
classCount.items()

dict_items([('B', 2), ('A', 1)])

In [29]:
import kNN

In [30]:
group, labels = kNN.createDataSet()

In [31]:
kNN.classify0([0, 0], group, labels, 3)

'B'